import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ARABIC_FONT, ARABIC_FONT_BASE64 } from "./arabicFont";

/** ===============================
 * 🧠 Get current user's name
 * =============================== */
function getCurrentUserName(): string {
  try {
    const stored = localStorage.getItem("user");
    if (!stored) return "Unknown User";
    const user = JSON.parse(stored);
    return (
      user.fullName ||
      user.name ||
      user.username ||
      user.email ||
      "Unknown User"
    );
  } catch {
    return "Unknown User";
  }
}

/** ===============================
 * 🧩 Flatten nested objects
 * =============================== */
function flattenObject(
  obj: Record<string, any>,
  prefix = ""
): Record<string, any> {
  return Object.keys(obj).reduce((acc: Record<string, any>, key) => {
    const value = obj[key];
    const newKey = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      Object.assign(acc, flattenObject(value, newKey));
    } else {
      acc[newKey] =
        typeof value === "boolean"
          ? value
            ? "Yes"
            : "No"
          : value ?? "";
    }
    return acc;
  }, {});
}

/** ===============================
 * 🧾 Export to Excel (.xlsx)
 * =============================== */
export function exportToExcel<T extends Record<string, any>>(
  data: T[],
  fileName: string
) {
  if (!data?.length) {
    alert("⚠️ No data available to export.");
    return;
  }

  const userName = getCurrentUserName();
  const timestamp = new Date().toLocaleString();
  const flattened = data.map((d) => flattenObject(d));

  const meta = [
    { Info: "📘 Student Dropout Support System Report" },
    { Info: `👤 Generated by: ${userName}` },
    { Info: `📅 Date: ${timestamp}` },
    {},
  ];

  const worksheet = XLSX.utils.json_to_sheet(meta);
  XLSX.utils.sheet_add_json(worksheet, flattened, { origin: -1 });

  const keys = Object.keys(flattened[0]);
  worksheet["!cols"] = keys.map((k) => ({ wch: Math.max(k.length * 1.2, 15) }));

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
  XLSX.writeFile(workbook, `${fileName}_${Date.now()}.xlsx`);
}

/** ===============================
 * 📄 Export to PDF (.pdf)
 * =============================== */

// 🧩 Extend jsPDF types
declare module "jspdf" {
  interface jsPDF {
    getNumberOfPages(): number;
  }
}

export function exportToPDF<T extends Record<string, any>>(
  data: T[],
  fileName: string,
  options?: { title?: string; subtitle?: string; logoUrl?: string }
) {
  if (!data?.length) {
    alert("⚠️ No data available to export.");
    return;
  }

  const userName = getCurrentUserName();
  const timestamp = new Date().toLocaleString();
  const flattened = data.map((d) => flattenObject(d));
  const headers = Object.keys(flattened[0]);
  const rows = flattened.map((item) =>
    headers.map((key) => String(item[key] ?? ""))
  );

  const doc = new jsPDF({
    orientation: "landscape",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();

  // ✅ Register Arabic font
  doc.addFileToVFS(`${ARABIC_FONT}.ttf`, ARABIC_FONT_BASE64);
  doc.addFont(`${ARABIC_FONT}.ttf`, ARABIC_FONT, "normal");

  /** ===== BLUE HEADER BAR ===== */
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 80, "F");

  const logo = options?.logoUrl || "/logo.png";
  try {
    doc.addImage(logo, "PNG", 40, 20, 40, 40);
  } catch {
    console.warn("⚠️ Logo not found, skipping...");
  }

  // Title in Arabic + English
  doc.setFont(ARABIC_FONT, "normal");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text(
    options?.title ||
      "منصة دعم الأطفال المنقطعين عن الدراسة / Student Dropout Support System",
    pageWidth / 2,
    40,
    { align: "center" }
  );

  doc.setFontSize(12);
  doc.text(options?.subtitle || "تقرير الأثر / Impact Report", pageWidth / 2, 60, {
    align: "center",
  });

  /** ===== META INFO ===== */
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Generated by: ${userName}`, 40, 100);
  doc.text(`Generated on: ${timestamp}`, pageWidth - 180, 100);

  /** ===== TABLE ===== */
  autoTable(doc, {
    startY: 120,
    head: [headers],
    body: rows,
    theme: "grid",
    styles: {
      font: ARABIC_FONT, // ✅ ensure Arabic works in table cells
      fontSize: 8,
      cellPadding: 4,
      overflow: "linebreak", // ✅ wrap long text
      halign: "center",
      valign: "middle",
      minCellHeight: 18,
    },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
    },
    alternateRowStyles: { fillColor: [245, 247, 255] },
    tableWidth: "auto",
    margin: { left: 40, right: 40 },
  });

  /** ===== FOOTER ===== */
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 25, {
      align: "center",
    });
  }

  doc.save(`${fileName}_${Date.now()}.pdf`);
}
